"""followers

Revision ID: 546d6519b50e
Revises: 98a0bc191be8
Create Date: 2020-02-28 17:57:17.323421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '546d6519b50e'
down_revision = '98a0bc191be8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
