"""empty message

Revision ID: d5c85b82e7ae
Revises: 7d197c796495
Create Date: 2020-05-15 23:48:37.751473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5c85b82e7ae'
down_revision = '7d197c796495'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evaluation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('continent', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('country', sa.String(length=30), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'role', ['role_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('evaluation', schema=None) as batch_op:
        batch_op.drop_column('country')
        batch_op.drop_column('continent')

    # ### end Alembic commands ###
